# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-22 00:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(default='example.com', null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('fee', models.FloatField(default=0.0)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('camera', models.CharField(choices=[('NK', 'Nikon'), ('OL', 'Olympus'), ('GP', 'Go-Pro')], default='NK', max_length=2)),
                ('services', models.CharField(choices=[('WD', 'Wedding'), ('GD', 'Graduation'), ('SP', 'Active/Sports')], default='WD', max_length=2)),
                ('photo_styles', models.CharField(choices=[('BW', 'Black and White'), ('CL', 'Color')], default='CL', max_length=2)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
