# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-28 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0003_auto_20171128_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='photo',
            field=models.ManyToManyField(related_name='album', to='imager_images.Photo'),
        ),
    ]
